version: '3.8'

services:
  postgresql:
    image: postgres:13.22-alpine3.22
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nestchat_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:8.2.0-alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - dev

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  dev:
    driver: bridge
